//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASVURU
    {
        public string BasvuruId { get; set; }
        public string BasvuruOgrenciId { get; set; }
        public string BasvuruTarihi { get; set; }
        public string BasvuruDuzenlemeTarihi { get; set; }
        public int BasvuruIptal { get; set; }
        public string BasvuruIptalTarihi { get; set; }
        public string BasvuruSinavId { get; set; }
        public string BasvuruDerslikId { get; set; }
    
        public virtual DERSLIK DERSLIK { get; set; }
        public virtual OGRENCI OGRENCI { get; set; }
        public virtual SINAV SINAV { get; set; }
    }
}
