//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAKULTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAKULTE()
        {
            this.DERSLIK = new HashSet<DERSLIK>();
            this.OGRENCI = new HashSet<OGRENCI>();
            this.OGRETIMELEMANI = new HashSet<OGRETIMELEMANI>();
        }
    
        public string FakulteId { get; set; }
        public string FakulteAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DERSLIK> DERSLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRENCI> OGRENCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRETIMELEMANI> OGRETIMELEMANI { get; set; }
    }
}
