//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANCIGIRIS
    {
        public string KullaniciId { get; set; }
        public string KGOEId { get; set; }
        public string KGOEDKullaniciAdi { get; set; }
        public string KGOEDSifre { get; set; }
        public string KGYetki { get; set; }
    
        public virtual OGRETIMELEMANI OGRETIMELEMANI { get; set; }
    }
}
