//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinavBasvuruEntities : DbContext
    {
        public SinavBasvuruEntities()
            : base("name=SinavBasvuruEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASVURU> BASVURU { get; set; }
        public virtual DbSet<DERSLIK> DERSLIK { get; set; }
        public virtual DbSet<FAKULTE> FAKULTE { get; set; }
        public virtual DbSet<KULLANCIGIRIS> KULLANCIGIRIS { get; set; }
        public virtual DbSet<OGRENCI> OGRENCI { get; set; }
        public virtual DbSet<OGRETIMELEMANI> OGRETIMELEMANI { get; set; }
        public virtual DbSet<OGRETIMELEMANIDERSLIK> OGRETIMELEMANIDERSLIK { get; set; }
        public virtual DbSet<SINAV> SINAV { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
