//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRETIMELEMANI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OGRETIMELEMANI()
        {
            this.KULLANCIGIRIS = new HashSet<KULLANCIGIRIS>();
            this.OGRETIMELEMANIDERSLIK = new HashSet<OGRETIMELEMANIDERSLIK>();
        }
    
        public string OEId { get; set; }
        public string OEAd { get; set; }
        public string OESoyad { get; set; }
        public string OEUnvan { get; set; }
        public string OEFakulteId { get; set; }
        public string OETel { get; set; }
        public string OEEposta { get; set; }
        public string OEKimlikNo { get; set; }
    
        public virtual FAKULTE FAKULTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KULLANCIGIRIS> KULLANCIGIRIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRETIMELEMANIDERSLIK> OGRETIMELEMANIDERSLIK { get; set; }
    }
}
