//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRETIMELEMANIDERSLIK
    {
        public string OEDId { get; set; }
        public string OEDerslikId { get; set; }
        public string OESinavId { get; set; }
        public string OEDOEId { get; set; }
    
        public virtual DERSLIK DERSLIK { get; set; }
        public virtual OGRETIMELEMANI OGRETIMELEMANI { get; set; }
        public virtual SINAV SINAV { get; set; }
    }
}
