//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavBasvuruApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINAV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINAV()
        {
            this.BASVURU = new HashSet<BASVURU>();
            this.OGRETIMELEMANIDERSLIK = new HashSet<OGRETIMELEMANIDERSLIK>();
        }
    
        public string SinavId { get; set; }
        public string SinavAd { get; set; }
        public string SinavDonem { get; set; }
        public string SinavZamani { get; set; }
        public string SinavTuru { get; set; }
        public string SinavDili { get; set; }
        public int SinavTamam { get; set; }
        public int SinavIptal { get; set; }
        public string SinavAciklama { get; set; }
        public string SinavBasvuruBaslama { get; set; }
        public string SinavBasvuruBitis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASVURU> BASVURU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRETIMELEMANIDERSLIK> OGRETIMELEMANIDERSLIK { get; set; }
    }
}
